### ISSUE TITLE
Bring back short imports

### ISSUE THREAD

**Issue by ElePT** [qiskit-community/qiskit-algorithms#5]
With the introduction of primitive-based algorithms we had 2 separate import paths for classes with the same name, so we enforced using the "long" import path to make the import process intentional, instead of allowing importing directly `from qiskit.algorithms`. For example:

`from qiskit.algorithms import VQE` used to do: `from qiskit.algorithms.minimum_eigen_solvers import VQE`, and it was replaced with `from qiskit.algorithms.minimum_eigensolvers import VQE` for the new VQE class (while `from qiskit.algorithms import VQE` would import the old class).

Now that the old paths have been deprecated and removed, we can bring back the short import path to point to the new classes, should we want to do it for convenience.

**Comment by woodsp-ibm** [comment]
This will also allow the algorithms to be documented as they were before were they are listed in the tables on that page - rather than some being there in a table and others just a link to a sub-module. Optimizers, gradients and fidelities I imagine would stay as a link to the module with them documented there as they have been.
